version: "3"

services:
  web:
    container_name: config-server
    restart: always
    build: .
    ports:
       - "8081:8081"
    links:
      - mongo
  mongo:
    container_name: mymongodatabase
    image: mongo
    ports:
      - "27017:27017"